apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-deployment
  labels:
    app: api-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
      - name: api-auth
        image: joelmndz/api_auth:latest
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"

        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: URI_AUTH

        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: SECRET
            
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: EMAIL_USER

        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: EMAIL_PASSWORD

        - name: CLOUDINARY_NAME
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: CLOUDINARY_NAME

        - name: CLOUDINARY_KEY
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: CLOUDINARY_KEY

        - name: CLOUDINARY_SECRET
          valueFrom:
            secretKeyRef:
              name: api-auth-secrets
              key: CLOUDINARY_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: api-auth-service
spec:
  type: NodePort

  selector:
    app: api-auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30100
      