apiVersion: v1
kind: Secret
metadata:
  name: api-banca-secrets
type: Opaque
data:
  SECRET: QkFOQ0FfVUxFQU0=
  EMAIL_USER: Ym9vdC5hc2lzdGVudGUuc2lzdGVtYUBnbWFpbC5jb20=
  EMAIL_PASSWORD: Z3N2eXFheHZzY2N0cGZmYQ==