apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodeexporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nodeexporter
  template:
    metadata:
      labels:
        role: nodeexporter
    spec:
      containers:
        - name: nodeexporter
          image: prom/node-exporter
          ports:
          - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: nodeexporter-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      name: http
  selector:
    role: nodeexporter