apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: default
data:
# El ip debe ser el que le asigne kubernetes al nodeexport
  prometheus.yml: |-    
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['10.110.177.114:9100']
          